### ISSUE TITLE
OutputFields not working with fields with dot notation

### ISSUE THREAD

**Issue by SPIRIT-Betrieb** [joernott/monitoring-check_log_elasticsearch#11]
The following action file config does not return the 2nd field. Only fields without dots are returned.

output_fields: ["message","thrown.message"]

**Comment by joernott** [comment]
a) Please check if "thrown.message" is listed in the "fields" part of the query definition for that rule. Example:
```yaml
actions:
  - name: 'my-java-app'
    index: 'my-java-app-*'
    query: '{"query":{"bool":{"must":[{"match":{"agent.hostname":"testvm"}}],"filter":[{"range":{"@timestamp":{"gt":"_TIMESTAMP_"}}}]}},,"fields":["@timestamp","message","agent.hostname","thrown.message"],"sort":[{"@timestamp":{"order":"asc", "format": "strict_date_optional_time_nanos", "numeric_type" : "date_nanos"}},{"_shard_doc": "desc"}],"_source":false,_PAGINATION_}'
```

b) If that is the case, I would need the config file used in this check and the anonymized json of the message in your elasticsearch you were expecting to show? Without this, it is hard for me to simulate this constellation locally
